---
- include: "{{ item }}"
  with_first_found:
    - "./setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "./setup-{{ ansible_distribution }}.yml"
    - "./setup-{{ ansible_os_family }}.yml"
    - "./setup-default.yml"

- name: Configure ZSH
  template:
    src=zshrc.j2
    dest={{ ansible_env.HOME }}/.zshrc
    backup=yes
  become_user: "{{ ansible_env.USER }}"

- name: Configure Shell to ZSH
  user:
    name={{ ansible_env.USER }}
    shell=/bin/zsh
  become: true
