---
- include_tasks: "{{ item }}"
  with_first_found:
    - "./setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "./setup-{{ ansible_distribution }}.yml"
    - "./setup-{{ ansible_os_family }}.yml"
    - "./setup-default.yml"
