---
# tasks file for ansible-role-buildessential
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: buildessential_packages is not defined

- name: Install Build Essential packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ buildessential_packages }}"
