- name: Add specific MacOS dependencies
  set_fact:
    build_essential_packages_extra: []

- name: Install Build Essential packages
  package:
    name: "{{ buildessential_item }}"
    state: present
  with_items: "{{build_essential_packages + build_essential_packages_extra | difference([]) }}"
  loop_control:
    loop_var: buildessential_item
