---
galaxy_info:
  author: jpolo
  description: Atom installation with APM
  company: 
  license: "license (BSD, MIT)"
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - editor
    - github
    - atom
  dependencies: []
