---
- include: "{{ item }}"
  with_first_found:
    - "./setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "./setup-{{ ansible_distribution }}.yml"
    - "./setup-{{ ansible_os_family }}.yml"
    - "./setup-default.yml"

- name: Add GIT diff.tool
  git_config:
    name: difftool.vscode.cmd
    scope: global
    value: "{{ visualstudiocode_git_diff if visualstudiocode_package_state != 'absent' else '' }}"
  become: false
