galaxy_info:
  author: jpolo
  description: ''
  company: ''
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: '2.0'
  platforms:
    - name: macOS
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []

dependencies: []
