---
- hosts: localhost
  connection: local
  remote_user: root
  vars:
    vscode_extensions:
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - ms-vsliveshare.vsliveshare
      - wayou.vscode-todo-highlight
      - gitlab.gitlab-workflow
      - github.vscode-pull-request-github
      - redhat.vscode-yaml
      # - VisualStudioExptTeam.vscodeintellicode
