---
- name: Ensure apt-transport-https is installed.
  apt:
    name: "{{ apt_transport_https_item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  loop_control:
    loop_var: apt_transport_https_item

- name: Add YARN apt key.
  apt_key:
    url: "{{yarn_apt_key_url}}"
    id: "{{yarn_apt_key_sig}}"
    state: present

- name: Add YARN repositories.
  apt_repository:
    repo: "{{ yarn_apt_repository }}"
    update_cache: yes
    state: present
    mode: 644

- name: Ensure YARN package is present
  apt:
    name: "{{yarn_package_name}}"
    state: "{{yarn_package_state}}"
