- name: Install Android Tools
  homebrew_cask:
    name: "{{androidtools_item}}"
    state: "{{androidtools_package_state}}"
  become: false
  with_items:
    - android-platform-tools
    - android-file-transfer
  loop_control:
    loop_var: androidtools_item

