galaxy_info:
  author: Julien Polo
  description: Installs pip
  company:
  license: BSD
  min_ansible_version: 1.9
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - development
    - python
    - pip
    - python-pip
dependencies: []
