---
galaxy_info:
  author: jpolo
  description: YARN installation
  company: ''
  license: "license (BSD, MIT)"
  min_ansible_version: '2.0'
  platforms:
    - name: macOS
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - npm
    - yarn
dependencies: []
