---
galaxy_info:
  author: jpolo
  description: YARN installation
  company:
  license: "license (BSD, MIT)"
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - npm
    - yarn
  dependencies: []
