- name: Enable Hashicorp tap
  homebrew_tap:
    name: hashicorp/tap
    state: "{{terraform_package_state}}"
  become: false

- name: Install Terraform
  package:
    name: "hashicorp/tap/terraform"
    state: "{{terraform_package_state}}"
  become: false
