- name: Install Java
  homebrew_cask:
    name: "{% if java_package_version is defined %}homebrew/cask-versions/java{{java_package_version}}{% else %}java{% endif %}"
    state: "{{java_package_state}}"
  when: java_package_version is defined
  become: false
