---
galaxy_info:
  author: jpolo
  description: Sketch installation
  company: ''
  license: "license (BSD, MIT)"
  min_ansible_version: '2.0'
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - sketch
dependencies: []
