---

- name: Find shell profile scripts
  stat:
    path: "{{ ansible_env.HOME }}/{{ item }}"
  with_items: "{{ nvm_shell_profile_scripts }}"
  register: nvm_shell_profile_stat

- name: Set NVM_DIR in shell profiles
  lineinfile:
    dest: "{{ ansible_env.HOME }}/{{ item.item }}"
    line: 'export NVM_DIR="$HOME/.nvm"'
    regexp: '^export NVM_DIR='
  with_items: "{{ nvm_shell_profile_stat.results }}"
  when: item.stat.exists

- name: Source nvm.sh in shell profiles
  lineinfile:
    dest: "{{ ansible_env.HOME }}/{{ item.item }}"
    line: '[ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh" # This loads nvm'
    insertafter: '^export NVM_DIR='
    regexp: "/nvm.sh"
  with_items: "{{ nvm_shell_profile_stat.results }}"
  when: item.stat.exists
