- set_fact:
    nvm_shell_profile_scripts:
      - .bashrc
      # - .zshrc

- name: Install NVM
  homebrew:
    name: "nvm"
    state: "{{nvm_package_state}}"
  become: false

- name: Configure RC Files
  blockinfile:
    path: "{{ ansible_env.HOME }}/{{ rcfile_item }}"
    backup: yes
    marker: "# {mark} NVM setup"
    insertbefore: EOF
    block: "{{ lookup('file', './templates/shellrc') }}"
    create: yes
    validate: "zsh %s"
  become_user: "{{ ansible_env.USER }}"
  with_items: "{{ nvm_shell_profile_scripts }}"
  loop_control:
    loop_var: rcfile_item
