---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Add Slack apt key.
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- name: Add Slack repositories.
  apt_repository:
    #repo:  "deb https://packagecloud.io/slacktechnologies/slack/{{ansible_distribution|lower}} {{ ansible_distribution_release }} main"
    repo: "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    update_cache: yes
    state: present
    mode: 644

- name: Ensure Slack package is present
  apt: "name=slack-desktop state=present"
