galaxy_info:
  author: Julien Polo
  description: Installs rbenv
  company: ''
  license: BSD
  min_ansible_version: '2.0'
  github_branch: master
  platforms:
    - name: macOS
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - ruby
    - rbenv
dependencies: []
