---
galaxy_info:
  author: jpolo
  description: Terminal installation
  company:
  license: "license (BSD, MIT)"
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  galaxy_tags:
    - term
    - cli
    - console
  dependencies: []
