name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        ./test/suite.sh
